repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black --check ./
        types: [python]
        language: system
        pass_filenames: false
    -   id: isort
        name: isort
        entry: isort --check-only ./
        types: [python]
        language: system
        pass_filenames: false
    -   id: flake8
        name: flake8
        entry: flake8 ./
        types: [python]
        language: system
        pass_filenames: false