# Generated by Django 4.0.6 on 2022-08-05 13:18

from django.db import migrations
from authentication.services import create_dev_user


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_auto_20220805_1602"),
    ]

    operations = [migrations.RunPython(create_dev_user)]
